### ISSUE TITLE
[BUG] JWT expired, infinite refreshes

### ISSUE THREAD

**Issue by JonasDaWi** [technologiestiftung/stadtpuls#18]
Sometimes, when I open the stadtpuls frontend - sensors page, i get an error message: "JWT expired" and the page refreshes every second. 
Linux Mint, latest firefox

**Comment by ff6347** [comment]
HI @JonasDaWi  Does that happen after the page was idle for some time? The JWT issued by supabase is valid for an hour. If you keep interacting with the site the JWT will be renewed all the time. If the tab stays open and you com back after that period it is expired. A refresh should fix that. 

Or does that happen when you login?

**Comment by JonasDaWi** [comment]
Hi @ff6347 yes it happens when the page was idle for some time, eg. over night. A refresh does not fix the issue. I think what fixed it for me was restarting firefox. I will record a video next time it happens

**Comment by ff6347** [comment]
Okay. Thank you. If you do the video please open the developer console so we can see the error messages. (F12 should open it)
